### ISSUE TITLE
"Spoty add replace and play" - the cursor jumps to one folder above!

### ISSUE THREAD

**Issue by norrest** [Saiyato/volumio-1.55-update#2]
After corrections, when I press "Spoty add replace and play" - the cursor jumps to one folder above!
"Add and play"  for USB / Webradio  now also - cursor jumps to one folder above!

**Comment by norrest** [comment]
https://github.com/norrest/volumio/blob/master/var/www/js/volumio.api.js
https://github.com/norrest/volumio/blob/master/var/www/js/volumio.playback.js

These are my corrected files! Can somehow combine with yours? Here, the arrow back in the main menu is always present! There is no sense after clicking play -
 Return back!

**Comment by Saiyato** [comment]
I have not reviewed your changes, but they have been committed nonetheless. I have not time to rig up another Volumio instance, since I'm developing against 2.x only.
